//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.02 at 11:31:05 AM WAT 
//


package com.bprogrammer.console.doc.integrify_console_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accountType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DocProvided" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SchemeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AccountCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeferralInPlace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeferralApprover" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeferralExpiryDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accountNumber",
    "accountType",
    "docProvided",
    "schemeCode",
    "accountCategory",
    "deferralInPlace",
    "deferralApprover",
    "deferralExpiryDate"
})
@XmlRootElement(name = "getIntegrifyDocRequest")
public class GetIntegrifyDocRequest {

    @XmlElement(required = true)
    protected String accountNumber;
    @XmlElement(required = true)
    protected String accountType;
    @XmlElement(name = "DocProvided", required = true)
    protected String docProvided;
    @XmlElement(name = "SchemeCode", required = true)
    protected String schemeCode;
    @XmlElement(name = "AccountCategory", required = true)
    protected String accountCategory;
    @XmlElement(name = "DeferralInPlace", required = true)
    protected String deferralInPlace;
    @XmlElement(name = "DeferralApprover", required = true)
    protected String deferralApprover;
    @XmlElement(name = "DeferralExpiryDate", required = true)
    protected String deferralExpiryDate;

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountType(String value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the docProvided property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocProvided() {
        return docProvided;
    }

    /**
     * Sets the value of the docProvided property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocProvided(String value) {
        this.docProvided = value;
    }

    /**
     * Gets the value of the schemeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemeCode() {
        return schemeCode;
    }

    /**
     * Sets the value of the schemeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemeCode(String value) {
        this.schemeCode = value;
    }

    /**
     * Gets the value of the accountCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountCategory() {
        return accountCategory;
    }

    /**
     * Sets the value of the accountCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountCategory(String value) {
        this.accountCategory = value;
    }

    /**
     * Gets the value of the deferralInPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeferralInPlace() {
        return deferralInPlace;
    }

    /**
     * Sets the value of the deferralInPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeferralInPlace(String value) {
        this.deferralInPlace = value;
    }

    /**
     * Gets the value of the deferralApprover property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeferralApprover() {
        return deferralApprover;
    }

    /**
     * Sets the value of the deferralApprover property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeferralApprover(String value) {
        this.deferralApprover = value;
    }

    /**
     * Gets the value of the deferralExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeferralExpiryDate() {
        return deferralExpiryDate;
    }

    /**
     * Sets the value of the deferralExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeferralExpiryDate(String value) {
        this.deferralExpiryDate = value;
    }

}
