//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.02 at 11:31:05 AM WAT 
//


package com.bprogrammer.console.doc.integrify_console_service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bprogrammer.console.doc.integrify_console_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bprogrammer.console.doc.integrify_console_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetIntegrifyDocRequest }
     * 
     */
    public GetIntegrifyDocRequest createGetIntegrifyDocRequest() {
        return new GetIntegrifyDocRequest();
    }

    /**
     * Create an instance of {@link GetConsoleDocRequest }
     * 
     */
    public GetConsoleDocRequest createGetConsoleDocRequest() {
        return new GetConsoleDocRequest();
    }

    /**
     * Create an instance of {@link GetConsoleDocResponse }
     * 
     */
    public GetConsoleDocResponse createGetConsoleDocResponse() {
        return new GetConsoleDocResponse();
    }

    /**
     * Create an instance of {@link ConsoleStatus }
     * 
     */
    public ConsoleStatus createConsoleStatus() {
        return new ConsoleStatus();
    }

    /**
     * Create an instance of {@link GetIntegrifyDocResponse }
     * 
     */
    public GetIntegrifyDocResponse createGetIntegrifyDocResponse() {
        return new GetIntegrifyDocResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

}
